version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"   # Mapea el puerto 4200
    volumes:
      - ./:/app       # Monta el c√≥digo para hot-reload
      - /app/node_modules  # Evita sobrescribir node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Mejora hot-reload en Docker